name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Executa quando fizer push na branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Usa uma VM Ubuntu para executar o job

    steps:
    - uses: actions/checkout@v3  # Clona o código do repositório

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Configura o builder do Docker

    - name: Login to Docker Hub
      uses: docker/login-action@v2  # Faz login no Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Usuário Docker Hub salvo nos Secrets do repo
        password: ${{ secrets.DOCKER_PASSWORD }}  # Senha Docker Hub salva nos Secrets do repo

    - name: Build and push
      uses: docker/build-push-action@v4  # Builda a imagem e envia para o Docker Hub
      with:
        push: true
        tags: thiagoduran/small-project:latest
